#!/bin/sh

DIR=`pwd`
USER=`stat -c %U .`

exec 2>&1

if [ -z $ENVDIR_RUN ]; then
    export ENVDIR_RUN=1
    echo "Reading envdir"
    exec chpst -e $DIR/env $0
fi

echo "Running npm ($NPM) install as $USER"

exec chpst -u $USER ${NPM:-/usr/bin/npm} install
